### ISSUE TITLE
browserify support?

### ISSUE THREAD

**Issue by rico345100** [gajus/babel-plugin-react-css-modules#30]
When I run this module with browserify, it fails with:

> Cannot read property 'replace' of undefined while parsing file:

Looks like there are same issues with Webpack, unfortunately no one uses browserify in this place :(
Anyway, some people like me, still prefer using Browserify + Gulp instead of Webpack.
Is there a way to solve this problem with Browserify now? If not, do you have plan to support it? I really impressed this module and really want to try with.

Thanks!

It's my gulp code:
```javascript
gulp.task('default', () => {
	return browserify({
		entries: ['./src/app.js'],
		debug: true
	})
	.transform(babelify, { 
		presets: ["es2015", "react"],
		plugins: [
			"babel-plugin-react-css-modules",
		]
	})
	.bundle()
	.on('error', swallowError)
	.pipe(source('app.js'))
	.pipe(buffer())
	.pipe(gulp.dest('./build'));
});
```

Error details:
```
TypeError: /Users/rico345100/Desktop/learn/browserifyTest/src/app.js: Cannot read property 'replace' of undefined
    at generate (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/generic-names/index.js:29:23)
    at exportScopedName (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:48:24)
    at localizeNode (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:64:28)
    at Array.map (native)
    at localizeNode (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:60:38)
    at traverseNode (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:78:20)
    at Array.map (native)
    at traverseNode (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at Array.map (native)
    at traverseNode (/Users/rico345100/Desktop/learn/browserifyTest/node_modules/postcss-modules-scope/lib/index.js:84:38)
```

**Comment by gajus** [comment]
> Cannot read property 'replace' of undefined while parsing file:

This was a bug that now has been fixed. (You can bypass the bug by explicitly configuring the `generateScopedName` option, https://github.com/gajus/babel-plugin-react-css-modules#configuration).

**Comment by gajus** [comment]
> Is there a way to solve this problem with Browserify now? If not, do you have plan to support it? I really impressed this module and really want to try with.

This plugin should work with Browserify (there is nothing webpack specific). Try the latest version.

**Comment by rico345100** [comment]
I just tested with latest version 2.1.1, it still fails with different error:

```
/Users/rico345100/Desktop/learn/browserifyTest/src/app.css:1
.table {
^
ParseError: Unexpected token
```

I just followed your example, it wasn't working at all with browserify + gulp. I used same gulp code above, and these are js codes:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import table from './app.css';

class App extends React.Component {
	render() {
		return (
			<div styleName='table.table'>
				<div styleName='table.row'>
					<div styleName='table.cell'>A1</div>
					<div styleName='table.cell'>B1</div>
					<div styleName='table.cell'>C1</div>
				</div>
			</div>
		);
	}
}

ReactDOM.render(
	<App />,
	document.getElementById('entry')
);
```

```css
.table {
	display: table;
}

.row {
	display: table-row;
}

.cell {
	display: table-cell;
	padding: 5px;
}

.cell:nth-child(1) {
	background: #f00;
}

.cell:nth-child(2) {
	background: #0f0;
}

.cell:nth-child(3) {
	background: #00f;
}

.yellow {
	background: #ff0!important;
}
```

Any solution please?
